version: "3.8"
services:
    db:
        image: postgres:latest
        container_name: pgDB
        ports:
        - "5432:5432"
        networks:
        - custom
        environment:
            POSTGRES_DB: "libreria"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "123"
        volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
        - db-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: on-failure:5
        container_name: pgAdmin
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "123"
            PGADMIN_LISTEN_PORT: "80"
        ports:
        - "8080:80"
        networks:
        - custom
        depends_on:
        - db

    scraper:
        build: 
            context: ./Container_C/
        container_name: pyscraper
        networks:
            - custom  
        depends_on: 
            - pgadmin
        env_file:
            - ./Container_C/env.list
        command: python3 ./scraper.py

volumes:
    db-data:
    pgadmin-data:

networks:
  custom:
        driver: bridge